from enum import Enum


class WorkflowStatus(str, Enum):
    CREATED = "CREATED"
    PLANNING = "PLANNING"
    POLICY_REVIEW = "POLICY_REVIEW"
    SIMULATING = "SIMULATING"
    WAITING_FOR_APPROVAL = "WAITING_FOR_APPROVAL"
    APPROVED_FOR_EXECUTION = "APPROVED_FOR_EXECUTION"
    EXECUTING = "EXECUTING"
    COMPLETED = "COMPLETED"
    PARTIALLY_COMPLETED = "PARTIALLY_COMPLETED"
    FAILED = "FAILED"
    BLOCKED = "BLOCKED"
    REJECTED = "REJECTED"
    CANCELLED = "CANCELLED"


class StepState(str, Enum):
    PENDING = "PENDING"
    PLANNED = "PLANNED"
    POLICY_ALLOWED = "POLICY_ALLOWED"
    POLICY_BLOCKED = "POLICY_BLOCKED"
    APPROVAL_REQUIRED = "APPROVAL_REQUIRED"
    SIMULATED = "SIMULATED"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"
    EXECUTING = "EXECUTING"
    SUCCEEDED = "SUCCEEDED"
    FAILED = "FAILED"
    SKIPPED = "SKIPPED"


class RiskLevel(str, Enum):
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
